-- SCHEMA FILE FOR BINGO

CREATE DATABASE bingo_db;

USE bingo_db;

CREATE TABLE bingo (
id INTEGER PRIMARY KEY,
name VARCHAR(50) NOT NULL,
s0 INTEGER NOT NULL,
s1 INTEGER NOT NULL,
s2 INTEGER NOT NULL,
s3 INTEGER NOT NULL,
s4 INTEGER NOT NULL,
s5 INTEGER NOT NULL,
s6 INTEGER NOT NULL,
s7 INTEGER NOT NULL,
s8 INTEGER NOT NULL,
s9 INTEGER NOT NULL,
s10 INTEGER NOT NULL,
s11 INTEGER NOT NULL,
s12 INTEGER NOT NULL,
s13 INTEGER NOT NULL,
s14 INTEGER NOT NULL,
s15 INTEGER NOT NULL,
s16 INTEGER NOT NULL,
s17 INTEGER NOT NULL,
s18 INTEGER NOT NULL,
s19 INTEGER NOT NULL,
s20 INTEGER NOT NULL,
s21 INTEGER NOT NULL,
s22 INTEGER NOT NULL,
s23 INTEGER NOT NULL,
s24 INTEGER NOT NULL,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);